### PR TITLE
Add reaction on typo to show suggested embed.

### PR DESCRIPTION
**Pull request by benwoo1110**
With the new "check for typo feature", this PR adds a way to show the best match embed based on the user's typo with a simple reaction.

Video if it working:
https://user-images.githubusercontent.com/30431861/113411951-aaf86280-93e9-11eb-944f-0f2dc89cb740.mp4

### CODE REVIEW

**Comment by Aberdeener** [comment]
:shipit:

**Comment by benwoo1110** [comment]
Realise there was a small merge conflict, just fixed that!

**Comment by lucko** [comment]
I've just resolved another merge conflict following Turbo's PR - could you confirm that this still functions as you expect? :)

**Comment by benwoo1110** [comment]
Alright I will test and update you shortly.

**Comment by benwoo1110** [comment]
Just a small issue which I just pushed a fix for it. Other than that, all good!

**Comment by lucko** [comment]
Cool, thanks!

**Pull request merged**
