### PR TITLE
Add velocityCheck command

### PR DESCRIPTION
**Pull request by OmegaWeaponDev**
Add a velocity check command as it requires different settings for online-mode than bungee

### CODE REVIEW

**Comment by NightSling** [comment]
@OmegaWeaponDev can you change the modern to specifiy "modern" or "bungeeguard" as modern only works on server 1.12 above and uses it's own system whereas bungeeguard just integrates itself into how bungeecord works

**Comment by OmegaWeaponDev** [comment]
> @OmegaWeaponDev can you change the modern to specifiy "modern" or "bungeeguard" as modern only works on server 1.12 above and uses it's own system whereas bungeeguard just integrates itself into how bungeecord works

This would assume users have BungeeGuard installed, which by not everyone will. So it's easier to leave as modern by default. People can change it to whatever they want. This is only a thing to check if they are getting uuid issues.

**Comment by NightSling** [comment]
> > @OmegaWeaponDev can you change the modern to specifiy "modern" or "bungeeguard" as modern only works on server 1.12 above and uses it's own system whereas bungeeguard just integrates itself into how bungeecord works
> 
> This would assume users have BungeeGuard installed, which by not everyone will. So it's easier to leave as modern by default. People can change it to whatever they want. This is only a thing to check if they are getting uuid issues.

Velocity refers to "BungeeGuard" as the bungeecord's built in system for fixing this UUID related problem. Wrong wording I know! I got confused at first too.

**Comment by powercasgamer** [comment]
> > > @OmegaWeaponDev can you change the modern to specifiy "modern" or "bungeeguard" as modern only works on server 1.12 above and uses it's own system whereas bungeeguard just integrates itself into how bungeecord works
> > 
> > 
> > This would assume users have BungeeGuard installed, which by not everyone will. So it's easier to leave as modern by default. People can change it to whatever they want. This is only a thing to check if they are getting uuid issues.
> 
> Velocity refers to "BungeeGuard" as the bungeecord's built in system for fixing this UUID related problem. Wrong wording I know! I got confused at first too.

It doesn't it's referring to [this](https://github.com/lucko/BungeeGuard)

**Review by powercasgamer — CHANGES_REQUESTED** [review]
Should add a link to the [PaperMC Docs](https://docs.papermc.io/velocity/player-information-forwarding#configuring-modern-forwarding-for-paper) and mention that `bungeecord` has to be set to `false` when using modern

**Review by powercasgamer — APPROVED** [review]

**Pull request merged**
